from typing import Tuple

class Const:
    """Constants used throughout the application."""
    
    # Root detection related paths
    ROOT_PATHS: Tuple[str, ...] = (
        "\"/system\"",
        "\"/system/bin\"",
        "\"/system/sbin\"",
        "\"/system/xbin\"",
        "\"/vendor/bin\"",
        "\"/sys\"",
        "\"/sbin\"",
        "\"/etc\"",
        "\"/proc\"",
        "\"/data/local\"",
        "\"/data/local/bin\"",
        "\"/data/local/xbin\"",
    )
    
    # Root detection related apps
    ROOT_APPS: Tuple[str, ...] = (
        "\"com.devadvance.rootcloak\"",
        "\"com.devadvance.rootcloakplus\"",
        "\"de.robv.android.xposed.installer\"",
        "\"com.saurik.substrate\"",
        "\"com.zachspong.temprootremovejb\"",
        "\"com.amphoras.hidemyroot\"",
        "\"com.amphoras.hidemyrootadfree\"",
        "\"com.formyhm.hiderootPremium\"",
        "\"com.formyhm.hideroot\"",
        "\"com.android.vending.billing.InAppBillingService.COIN\"",
        "\"com.android.vending.billing.InAppBillingService.LUCK\"",
        "\"com.chelpus.luckypatcher\"",
        "\"com.blackmartalpha\"",
        "\"org.blackmart.market\"",
        "\"com.allinone.free\"",
        "\"com.repodroid.app\"",
        "\"org.creeplays.hack\"",
        "\"com.baseappfull.fwd\"",
        "\"com.zmapp\"",
        "\"com.dv.marketmod.installer\"",
        "\"org.mobilism.android\"",
        "\"com.android.wp.net.log\"",
        "\"com.android.camera.update\"",
        "\"cc.madkite.freedom\"",
        "\"com.solohsu.android.edxp.manager\"",
        "\"org.meowcat.edxposed.manager\"",
        "\"com.xmodgame\"",
        "\"com.cih.game_cih\"",
        "\"com.charles.lpoqasert\"",
        "\"catch_.me_.if_.you_.can_\"",
        "\"com.koushikdutta.rommanager\"",
        "\"com.koushikdutta.rommanager.license\"",
        "\"com.dimonvideo.luckypatcher\"",
        "\"com.chelpus.lackypatch\"",
        "\"com.ramdroid.appquarantine\"",
        "\"com.ramdroid.appquarantinepro\"",
        "\"com.noshufou.android.su\"",
        "\"com.noshufou.android.su.elite\"",
        "\"eu.chainfire.supersu\"",
        "\"com.koushikdutta.superuser\"",
        "\"com.thirdparty.superuser\"",
        "\"com.yellowes.su\"",
        "\"com.topjohnwu.magisk\"",
        "\"com.kingroot.kinguser\"",
        "\"com.kingo.root\"",
        "\"com.smedialink.oneclickroot\"",
        "\"com.zhiqupk.root.global\"",
        "\"com.alephzain.framaroot\"",
        "\"busybox\"",
        "\"su\"",
        "\"magisk\"",
        "\"/su/xbin\"",
        "\"/magisk/.core/bin\"",
        "\"/system/lib/libxposed_art.so\"",
        "\"/system/lib64/libxposed_art.so\"",
        "\"/system/xposed.prop\"",
        "\"/cache/recovery/xposed.zip\"",
        "\"/system/framework/XposedBridge.jar\"",
        "\"/system/bin/app_process64_xposed\"",
        "\"/system/bin/app_process32_xposed\"",
        "\"/magisk/xposed/system/lib/libsigchain.so\"",
        "\"/magisk/xposed/system/lib/libart.so\"",
        "\"/magisk/xposed/system/lib/libart-disassembler.so\"",
        "\"/magisk/xposed/system/lib/libart-compiler.so\"",
        "\"/system/bin/app_process32_orig\"",
        "\"/system/bin/app_process64_orig\"",
        "\"/system/lib/libmemtrack_real.so\"",
        "\"/system/lib64/libmemtrack_real.so\"",
        "\"/system/lib/libriru_edxp.so\"",
        "\"/system/lib64/libriru_edxp.so\"",
        "\"/system/lib/libwhale.edxp.so\"",
        "\"/system/lib64/libwhale.edxp.so\"",
        "\"/system/framework/edxp.jar\"",
        "\"mobi.acpm.sslunpinning\"",
        "\"mobi.acpm.inspeckage\"",
        "\"com.mwr.dz\"",
        "\"XposedBridge.jar\"",
        "\"edxp.jar\"",
        "\"/system/app/Superuser.apk\"",
        "\"Superuser.apk\"",
        "\"/data/magisk/resetprop\"",
        "\"which su\"",
        "\"test-keys\"",
        "\"/system/xbin/which\"",
        "\"daemonsu\"",
        "\"/system/bin/su\"",
        "\"supersu\"",
        "\"/system/xbin/daemonsu\"",
        "\"/system/su\"",
        "\"/system/app\"",
        "\"/system/app/Superuser\"",
        "\"/system/bin/.ext/.su\"",
        "\"/system/usr/we-need-root/su-backup\"",
        "\"clesses.dex\"",
        "\"ro.debuggable\"",
        "\"ro.secure\""
    )
    
    # Emulator detection related values
    EMULATOR_NUMBERS: Tuple[str, ...] = (
        "\"15555215554\"",
        "\"15555215556\"",
        "\"15555215558\"",
        "\"15555215560\"",
        "\"15555215562\"",
        "\"15555215564\"",
        "\"15555215566\"",
        "\"15555215568\"",
        "\"15555215570\"",
        "\"15555215572\"",
        "\"15555215574\"",
        "\"15555215576\"",
        "\"15555215578\"",
        "\"15555215580\"",
        "\"15555215582\"",
        "\"15555215584\"",
        "\"000000000000000\"",
        "\"e21833235b6eef10\"",
        "\"012345678912345\"",
        "\"310260000000000\"",
    )
    
    EMULATOR_PATHS: Tuple[str, ...] = (
        "\"/dev/socket/genyd\"",
        "\"/dev/socket/baseband_genyd\"",
        "\"/dev/socket/qemud\"",
        "\"/dev/qemu_pipe\"",
        "\"ueventd.android_x86.rc\"",
        "\"x86.prop\"",
        "\"ueventd.ttVM_x86.rc\"",
        "\"init.ttVM_x86.rc\"",
        "\"fstab.ttVM_x86\"",
        "\"fstab.vbox86\"",
        "\"init.vbox86.rc\"",
        "\"ueventd.vbox86.rc\"",
        "\"fstab.andy\"",
        "\"ueventd.andy.rc\"",
        "\"fstab.nox\"",
        "\"init.nox.rc\"",
        "\"ueventd.nox.rc\"",
        "\"/BigNoxGameHD\"",
        "\"/YSLauncher\"",
        "\"/Android/data/com.bluestacks.home\"",
        "\"/Android/data/com.bluestacks.settings\"",
        "\"init.svc.qemud\"",
        "\"init.svc.qemu-props\"",
        "\"qemu.hw.mainkeys\"",
        "\"qemu.sf.fake_camera\"",
        "\"qemu.sf.lcd_density\"",
        "\"ro.bootloader\"",
        "\"ro.bootmode\"",
        "\"ro.hardware\"",
        "\"ro.kernel.android.qemud\"",
        "\"ro.kernel.qemu.gles\"",
        "\"ro.kernel.qemu\"",
        "\"ro.product.device\"",
        "\"ro.product.model\"",
        "\"ro.product.name\"",
        "\"ro.serialno\"",
        "\"10.0.2.15\"",
        "\"com.google.android.launcher.layouts.genymotion\"",
        "\"com.bluestacks\"",
        "\"com.bignox.app\"",
        "\"com.vphone.launcher\"",
        "\"nox\"",
        "\"generic\"",
        "\"google_sdk\"",
        "\"droid4x\"",
        "\"emulator\"",
        "\"Android SDK built for x86\"",
        "\"genymotion\"",
        "\"goldfish\"",
        "\"vbox86\"",
        "\"android_x86\"",
        "\"ranchu\"",
        "\"/system/bin/netcfg\"",
        "\"wlan0\"",
        "\"tunl0\"",
        "\"eth0\"",
        "\"android.os.SystemProperties\""
    )
    
    # Combine all values
    all_root_values: Tuple[str, ...] = ROOT_PATHS + ROOT_APPS
    all_emulator_values: Tuple[str, ...] = EMULATOR_NUMBERS + EMULATOR_PATHS